"""empty message

Revision ID: 241553e4489e
Revises: 7cad51269921
Create Date: 2021-04-17 17:07:31.655747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241553e4489e'
down_revision = '7cad51269921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('_id', name='user_pkey')
    )
    # ### end Alembic commands ###
