"""empty message

Revision ID: 7cad51269921
Revises: d1126b145798
Create Date: 2021-04-17 16:34:05.450640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cad51269921'
down_revision = 'd1126b145798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_url', 'url',
               existing_type=sa.CHAR(length=1200),
               type_=sa.String(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_url', 'url',
               existing_type=sa.String(length=5000),
               type_=sa.CHAR(length=1200),
               existing_nullable=True)
    # ### end Alembic commands ###
